#!/bin/bash
# 创建作品条目(需要 BLOG_BASE_URL/BLOG_ADMIN_USER/BLOG_ADMIN_PASS 已 export)
# 用法: create-work.sh <cover_url>
set -e
BLOGCTL=/Users/joe/code/joewang-studio/.claude/skills/blog-admin/cli/target/release/blogctl

$BLOGCTL works create --title "Token Foundry — LLM Inference & Training in 3D" --year 2026 --status live \
  --tags "Interactive 3D · three.js" --cap "" --order 9 \
  --cover "$1" \
  --link "https://llm-visual.wangchao0126.workers.dev" --role "Generated by Claude" \
  --description "A six-story translucent 'word foundry' that acts out how a large language model actually works. In inference mode, an orb of activations climbs the Transformer stack floor by floor — attention arcs reach back into a 16×6 KV-cache lattice, the LM head raises top-5 probability bars on the roof, a sampled token flies back to the end of the sequence, and the whole trip repeats autoregressively. In training mode the factory runs night shifts: green forward waves, cross-entropy scoreboards, orange backprop waves cascading down with gradient sparks, and a loss curve that converges over 60 steps. Click any candidate bar to force-sample a token; temperature, playback speed, cameras and lighting are all adjustable."
