#!/bin/bash
# 创建 4 个作品条目(需要 BLOG_BASE_URL/BLOG_ADMIN_USER/BLOG_ADMIN_PASS 已 export)
# 用法: create-works.sh <air_cover_url> <oled_cover_url> <ps5_cover_url> <domino_cover_url>
set -e
BLOGCTL=/Users/joe/code/joewang-studio/.claude/skills/blog-admin/cli/target/release/blogctl

$BLOGCTL works create --title "Arctic Breeze — AC Teardown" --year 2026 --status live \
  --tags "Interactive 3D · three.js" --cap "" --order 5 \
  --cover "$1" \
  --link "https://air-condition.pages.dev" --role "Generated by Claude" \
  --description "A 1.5-hp split air conditioner with all 33 parts hand-modeled from three.js primitives — zero external models or textures, every texture painted on Canvas. Watch it assemble part by part, blow the whole machine into a labeled exploded view, then power it on: the cross-flow fan spins, louvers sweep, cold air sinks and pools across the floor — and heat mode reverses the cycle, courtesy of the four-way valve."

$BLOGCTL works create --title "Polar Night — OLED TV" --year 2026 --status live \
  --tags "Interactive 3D · three.js" --cap "" --order 6 \
  --cover "$2" \
  --link "https://oled-tv.pages.dev" --role "Generated by Claude" \
  --description "A 65-inch 4K OLED TV in a full living-room scene, 21 parts hand-modeled from three.js primitives with Canvas-painted textures. The panel stack builds layer by layer — panel, flex cables, T-CON, graphite film, boards — and explodes toward the viewer like a mille-feuille. In watch mode the screen genuinely lights the room via RectAreaLight: aurora reel, test bars, or a synthwave racing game with signal pulses running down the HDMI cable."

$BLOGCTL works create --title "White Night V — Console Teardown" --year 2026 --status live \
  --tags "Interactive 3D · three.js" --cap "" --order 7 \
  --cover "$3" \
  --link "https://wn5-console.pages.dev" --role "Generated by Claude" \
  --description "A fictional white game console — an homage to a famous teardown video — standing on a gamer-room desk. 20 parts from motherboard, liquid metal and heat spreader to dust catchers and white side panels. One-click exploded view floats the internals above the desk; game mode lights the monitor, breathes the LED strips, and ties fan RPM to live SoC temperature and noise readouts."

$BLOGCTL works create --title "Domino Pitch — 1,095 Falling Dominoes" --year 2026 --status live \
  --tags "Physics Sim · Rapier WASM" --cap "" --order 8 \
  --cover "$4" \
  --link "https://domino-pitch.pages.dev" --role "Generated by Claude" \
  --description "A football pitch stacked with 1,095 giant dominoes along a 1.1 km three-dimensional course: snake runs, a forked spiral, an 11-step staircase, a 4.6 m skybridge, a diving relay, a 15×11 V-wave array, and a finale that knocks a giant football into the goal. Every fall is real rigid-body physics — Rapier WASM, one InstancedMesh, a single draw call — with no scripted animation anywhere."
